### ISSUE TITLE
RTIC scheduled software tasks consume TIMER, preventing use of Timer/Alarm hardware interrupts 

### ISSUE THREAD

**Issue by xabra** [rp-rs/rp-hal#458]
When using RTIC, if one wants to be able to schedule a software task (eg `taskname::spawn_after(duration)`) it is necessary to bind the TIMER peripheral to the monotonic:  ` let mono = Rp2040Monotonic::new(c.device.TIMER);`.  This makes the Timer peripheral and its four  hardware Alarm interrupts unavailable.

It would be useful to have Timer/Alarm hardware interrupts _and_ scheduled software tasks available simultaneously.  For example, to set key timing cycles using low overhead HW interrupts, and schedule SW tasks relative to them.

Perhaps deriving the monotonic from SYSTICK rather then TIMER would work.

**Comment by ithinuel** [comment]
Thanks for reporting this.

the implementation of monotonic you are refering to lives in an other repository .

Would you mind giving a try at : https://github.com/ithinuel/rp-hal/tree/impl-rtic-monotonic
When the feature `rtic-monotonic` is enabled, this adds a new type under [`rp2040_hal::timer::monotonic`](https://github.com/ithinuel/rp-hal/blob/impl-rtic-monotonic/rp2040-hal/src/timer.rs#L386-L430) that supports rtic's monotonic as well as taking any of the 4 alarm types while still giving access to the under lying timer to take other alarms if/when needed.

If you are already using the latest hal you should be able to add the following snippet to your `Cargo.toml` (you may face breakage on some components, like pio, that have evolved since last release):

```toml
[patch.crates-io]
rp2040-hal = { git = "https://github.com/ithinuel/rp-hal", branch = "impl-rtic-monotonic" }
rp-pico = { git = "https://github.com/ithinuel/rp-hal", branch = "impl-rtic-monotonic" }
# or-another-bsp = { git = "https://github.com/ithinuel/rp-hal", branch = "impl-rtic-monotonic" }
```

If this works for you I'll make a PR out of it.
